Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Elberth Morais
// Descrição   : Pontuação Time
// Autor(a)    : Maria Eduarda
// Data atual  : 09/02/2022
Var
n, qv, qe, p: real
Inicio
escreval (" Nome do Time")
leia(n)
escreval (" Quantidade de Vitórias")
leia(qv)
escreval (" Quantidade de Empates")
leia(qe)
p<-(qv*3)+qe
escreval (" Pontuação Campeonato",p)
Fimalgoritmo